Repository sparsh44/TextToSpeechAssistant, pull requests merged in 2025-03, with the labels that each got.

#11 Added responsiveness to the app (solved #4)
  react-speech-app/src/App.css
  react-speech-app/src/App.jsx
  react-speech-app/src/index.css
Labels: pwoc, easy

#14 Added real-time speech rate control functionality (#7 solved)
  react-speech-app/src/App.jsx
Labels: pwoc, easy

#19 #9 Implemented Dark Mode and White Mode and enhanced the UI
  react-speech-app/package-lock.json
  react-speech-app/package.json
  react-speech-app/src/App.jsx
  react-speech-app/src/app2.css
  react-speech-app/src/appremp.css
Labels: pwoc, medium

#21 Added the auto scroll and highlighting text feature and improved rate control…
  react-speech-app/src/App.css
  react-speech-app/src/App.jsx
  react-speech-app/src/app2.css
  react-speech-app/src/appremp.css
Labels: pwoc, hard
